<?php
    $lang['number']   = 'Reference';
    $lang['date']     = 'Billing date';
    $lang['time']     = 'Billing time';
    $lang['due']      = 'Due date';
    $lang['to']       = 'Client';
    $lang['from']     = 'Institution';
    $lang['product']  = 'Product';
    $lang['qty']      = 'Qty';
    $lang['price']    = 'Price';
    $lang['discount'] = 'Discount';
    $lang['vat']      = 'Vat';
    $lang['total']    = 'Total';
    $lang['page']     = 'Page';
    $lang['page_of']  = 'of';
    $lang['intermediate']  = 'Intermediate';
    $lang['model']  = 'Model';
    $lang['schedule']  = 'Schedule';
