<?php
    $lang['number']   = 'Référence';
    $lang['date']     = 'Date de facturation';
    $lang['time']     = 'Heure de facturation';
    $lang['due']      = 'Date d\'échéance';
    $lang['to']       = 'À';
    $lang['from']     = 'Facturé par';
    $lang['product']  = '';
    $lang['qty']      = 'Quantité';
    $lang['price']    = 'Prix TTC';
    $lang['discount'] = 'Réduction';
    $lang['vat']      = 'TVA';
    $lang['total']    = 'Total';
    $lang['page']     = 'Page';
    $lang['page_of']  = 'sur';
    $lang['intermediate']  = 'Par l\'intermédaire de';
    $lang['model']  = 'Modèle';
    $lang['schedule']  = 'Horaire';
